from random import randrange
# var = input('Please enter something: ')
# print('you entered ' + str(var))
mamethali3 = [None] * 20
mamethali2 = [None] * 447
mamethali = [
	["Ada ya mja hunena, mwungwana ni kitendo.","It is customary for a slave to talk, but a free man acts. (Mja is only used in this way in this proverb, otherwise it would be - a foreigner)", "UNPOSTED"],
	["Adhabu ya kaburi, aijua maiti.", "The torture of the grave is known only to the dead.", "UNPOSTED"],
	["Ahadi ni deni.", "A promise is a debt.", "UNPOSTED"],
	["Aibu ya maiti, aijua mwosha.", "Only a Moritician knows the real shame of the dead.", "UNPOSTED"],
	["Akiba haiozi.", "A reserve(savings) does not decay.", "UNPOSTED"],
	["Aisifuye mvua, imemnyea.", "He who praises rain has been rained on himself.", "UNPOSTED"],
	["Ajidhaniye amesimama, aangalie asianguke.", "He who thinks he is standing should be careful he doesn't fall.", "UNPOSTED"],
	["Akiba haiozi.", "A reserve does not decay.", "UNPOSTED"],
	["Akikaanga, tu chini ya gae.", "When he fries, we are under the frying pan. (Somebody always finds out a secret)", "UNPOSTED"],
	["Akili ni mali.", "Cleverness is wealth.", "UNPOSTED"],
	["Akili ni nywele; kila mtu ana zake.", "Reasoning is like hair, every person has his own.", "UNPOSTED"],
	["Akili nyingi huondowa maarifa.", "Too much wit diminishes wisdom.", "UNPOSTED"],
	["Akipenda, chongo huita kengeza.", "If he loves, he will call a one-eyed person a squinter. (Love is blind)", "UNPOSTED"],
	["Akumulikaye mchana; usiku akuchoma.", "He who shines a light on you during the day, sets fire to you during the night. (shows your inconsistencies and destroys your reputation at night)", "UNPOSTED"],
	["Akupaye kisogo si mwenzio.", "He who turns his back on you is not your friend.", "UNPOSTED"],
	["Akutendaye mtende; mche asiyekutenda.", "Harm him who harms you and fear him who harms you not.", "UNPOSTED"],
	["Alalaye usimwamshe; ukimwamsha, utalala wewe.", "Don't awake the asleep; if you awake him, remember you too will sleep.", "UNPOSTED"],
	["Alisifuyejua, limemwangaza.", "He who praised the sun, now has the sun shining on him.", "UNPOSTED"],
	["Aliyekando, haangukiwi na mti.", "He who stays to the side will not be hit by a falling tree.", "UNPOSTED"],
	["Aliyekupa wewe kiti, ndiye alinipa mimi kumbi.", "He who gave you a chair(throne) is the one who gave me a coconut husk. (Do not despise me because of my station in life)", "UNPOSTED"],
	["Aliyetota, hajui kutota.", "He who has drowned, does not know how to drown. (If you have nothing, you know not poverty)", "UNPOSTED"],
	["Amani haipatikani ila kwa ncha ya upanga.", "Peace is not possible except by the point of a sword.", "UNPOSTED"],
	["Amnyimae punda adesi, kampunguzia mashuzi.", "He who withholds lentils from a donkey, reduces the donkey's farts.", "UNPOSTED"],
	["Ana hasira za mkizi.", "He is as angry as a cuttlefish(fish which jump out of the water and land on the boat or beach, killing itself). (Out of the frying pan and into the fire)", "UNPOSTED"],
	["Anayekataa wengi ni mchawi.", "He who does not like crowds(company) is a sorcerer.", "UNPOSTED"],
	["Anayekuja pasina hodi, huondoka pasina kuaga.", "He who comes without asking to enter, will leave without saying goodby.", "UNPOSTED"],
	["Anayeonja asali, huchonga mzinga.", "He who tastes honey will build a hive.", "UNPOSTED"],
	["Anayetaka hachoki; hata akichoka kishapata.", "He who wants does not tire; when he tires he has what he wants.", "UNPOSTED"],
	["Angeenda juu kipungu, hafikilii mbinguni.", "Even though the hawk flies high, it does not reach heaven.", "UNPOSTED"],
	["Angurumapo simba, mcheza nani?", "Where the lion roars, who will play?", "UNPOSTED"],
	["Aninyimae mbuzi kanipunguzia mashuzi.", "He who withholds goat meat from me, reduces my farting.", "UNPOSTED"],
	["Apewaye ndiye aongezwaye.", "He who is given is the one who is given even more.", "UNPOSTED"],
	["Asiyebahati habahatiki(shi).", "He who is unlucky is never lucky.", "UNPOSTED"],
	["Asiyefunzwa na mamaye, hufunzwa na ulimwengu.", "He who is not taught by his mother, is taught by the world.", "UNPOSTED"],
	["Asiyejua maana, haambiwi maana.", "He who does not know reason cannot be told reason.", "UNPOSTED"],
	["Asiyekubali kushindwa, si mshindani.", "He who does not admit defeat or agree to lose, is not a competitor or debator.", "UNPOSTED"],
	["Asiyekujua hakuthamini.", "He who does not know you, does not value you.", "UNPOSTED"],
	["Asiyekuwapo machoni, na moyoni hayupo.", "He who is not in sight, is not in the heart.", "UNPOSTED"],
	["Out of sight; out of mind.", "Asiyekuwapo na lake halipo.", "UNPOSTED"],
	["He who is absent loses his share.", "Asiye na mengi, ana machache.", "UNPOSTED"],
	["He who does not have much, has few problems.", "Asiyesikia la mkuu(wazee), huona makuu(huvunja guu) He who does not listen to the leader(elders), comes to grief(breaks a leg).", "UNPOSTED"],
	["Asiyeuliza, hanalo ajifunzalo.", "He who does not ask, does not have what he needs to learn.", "UNPOSTED"],
	["Atangaye sana na jua hujuwa.", "He who always wanders around in the sun(by day) learns much. The more you see, the more you learn. Keep your eyes open.", "UNPOSTED"],
	["Atangazaye mirimo si mwana wa ruwari.", "The one who announces the tasks is not necessarily the son of the Liwali(headman).", "UNPOSTED"],
	["Auguaye huangaliwa.", "He who is sick is cared for.", "UNPOSTED"],
	["Avuaye nguo huchutama.", "He who removes his clothes, squats.", "UNPOSTED"],
	["Baada ya dhiki faraja.", "After hardship comes relief. After a storm there is calm.", "UNPOSTED"],
	["Bamba na waume ni bamba; hakuna bamba la mume.", "A council of many men is a council; there is no council of one man alone.", "UNPOSTED"],
	["Baniani mbaya kiatu chake dawa.", "A bad Indian thinks his boot is the best medicine.", "UNPOSTED"],
	["Bendera hufuata upepo.", "A flag follows the direction of the wind.", "UNPOSTED"],
	["Bilisi wa mtu ni mtu.", "The evil spirit of a man is in him. (He is his own worst enemy).", "UNPOSTED"],
	["Cha mlevi huliwa na mgema.", "The drunkard's money is consumed by the palm-wine trapper.", "UNPOSTED"],
	["Chanda chema huvikwa pete.", "A handsome finger gets the ring.", "UNPOSTED"],
	["Chema chajiuza, kibaya chajitembeza.", "A good thing sells itself, a bad thing treads on itself(is hawked).", "UNPOSTED"],
	["Chombo cha kuzama(kuvunja) hakina usukani(rubani).", "A sunk vessel(damaged) has no rudder(helmsman). What is predestined is inevitable.", "UNPOSTED"],
	["Chovya - chovya yamaliza buyu la asali.", "Constant dripping will empty the gourd of honey.", "UNPOSTED"],
	["Dalili ya mvua mawingu.", "The sign of rain - clouds .", "UNPOSTED"],
	["Damu nzito kuliko maji.", "Blood is thicker than water.", "UNPOSTED"],
	["Dau la mnyonge haliendi joshi; likienda joshi ni mungu kupenda.", "The inattentive man's boat does not go straight ahead; if it does it is because god wills it.", "UNPOSTED"],
	["Dawa ya moto ni moto.", "The remedy to fire is fire. Fire must be met with fire.", "UNPOSTED"],
	["Dua la kuku halimpati mwewe.", "The curse of the fowl does not bother the kite.", "UNPOSTED"],
	["Fadhila ya punda ni mateke.", "The gratitude of a donkey is a kick.", "UNPOSTED"],
	["Fadhili ya nyuki ni moto.", "A bee's thanks is fire. i.e. Bees are smoked out for their honey.", "UNPOSTED"],
	["Fimbo ya mbali hayiuwi nyoka.", "A distant weapon does not kill a snake.", "UNPOSTED"],
	["Fuata nyuki ule asali.", "Follow bees and you will eat honey.", "UNPOSTED"],
	["Fumbo mfumbe mjinga mwerevu huligangua.", "A riddle to a fool is unsolvable but a clever person will solve it.", "UNPOSTED"],
	["Ganda la muwa la jana chungu kaona kivuno.", "The skin of yesterday's sugarcane is a havest to an ant.", "UNPOSTED"],
	["Haba na haba hujaza kibaba.", "Little by little fills up the measure.", "UNPOSTED"],
	["Hapana marefu yasio na mwisho.", "There is no distance that has no end.", "UNPOSTED"],
	["Hakuna msiba usio na mwenziwe.", "There is no unaccompanied misfortune.", "UNPOSTED"],
	["Hakuna siri ya watu wawili.", "There is no secret between two people.", "UNPOSTED"],
	["Hakuna zaidi mbovu.", "There is no increase in that which is rotten.", "UNPOSTED"],
	["Hamadi ni iliyo bindoni; silaha ni iliyo mkononi.", "That which you have in your pocket is your safeguard; that which you have in your hand is your weapon.", "UNPOSTED"],
	["Haraka haraka haina baraka.", "To be in a hurry has no blessing.", "UNPOSTED"],
	["Hasira, hasara.", "Anger brings loss(damage).", "UNPOSTED"],
	["Heri kufa macho kuliko kufa moyo.", "It is better to lose your eyesight than to lose heart.", "UNPOSTED"],
	["Heri kukwaa kidole kuliko kukwaa ulimi.", "Better to stumble with the toe than the tongue.", "UNPOSTED"],
	["Heri kujikwa kidole kuliko ulimi.", "It is better to stub your toe than your toungue.", "UNPOSTED"],
	["Hiari ya shinda utumwa.", "To volunteer is better than to be forced. To have a choice is better than not.", "UNPOSTED"],
	["Ihsani (hisani)haiozi.", "Kindness does does not rot.", "UNPOSTED"],
	["Ikiwa hujui kufa,tazama kaburi.", "If you don't know death, look at the grave.", "UNPOSTED"],
	["Jina jema hung'ara gizani.", "A good name shines in the dark.", "UNPOSTED"],
	["Jino la pembe si dawa ya pengo.", "An ivory tooth is not a cure for a gap(lost tooth).", "UNPOSTED"],
	["Jitihadi haiondoi kudura.", "Great effort does is not a substitute for faith.", "UNPOSTED"],
	["Jogoo la shamba haliwiki mjini.", "The village cock does not crow in town.", "UNPOSTED"],
	["Kafiri akufaye si Isilamu asiyekufa.", "When an infidel dies it is not like a Muslim who has not died. (The death of a non-believer is not of concern to a believer or is not as important as the believer who is alive)", "UNPOSTED"],
	["Kamba hukatika pabovu.", "A rope breaks where it is rotten.", "UNPOSTED"],
	["Kanga hazai ugenini.", "A guinea fowl does not lay eggs in strange places.", "UNPOSTED"],
	["Kawaida ni kama sheria.", "Routine(status quo)is like(becomes)the law.", "UNPOSTED"],
	["Kawia ufike.", "It is better to delay in order to ensure arrival.", "UNPOSTED"],
	["Kazi mbaya siyo mchezo mwema.", "To do a poor job is not a good game(idea).", "UNPOSTED"],
	["Kelele za mlango haziniwasi usingizi.", "The creakings of the door deprives me of no sleep.", "UNPOSTED"],
	["Kenda karibu na kumi.", "Nine is near ten.", "UNPOSTED"],
	["Kiburi si maungwana.", "Arrogance is not gentlemanly.", "UNPOSTED"],
	["Kichango kuchangizana.", "A fund raising is for everyone to contribute.", "UNPOSTED"],
	["Kidole kimoja hakivunji chawa.", "One finger canot kill a louse.", "UNPOSTED"],
	["Kilimia kikizama kwa jua huzuka kwa mvua, kikizama kwa mvua huzuka kwa jua.", "When the Pleiades set in sunlight(clear)they rise in rain; when they set in rain they rise in sunlight.", "UNPOSTED"],
	["Kingiacho mjini si haramu.", "That which is fashionable in town is never prohibited.", "UNPOSTED"],
	["Kikulacho ki nguoni mwako.", "That which eats you is in your clothing.", "UNPOSTED"],
	["Kila chombo kwa wimblile.", "Every vessel has its own waves.", "UNPOSTED"],
	["Kila mlango na ufunguo wake.", "Every door has it's own key.", "UNPOSTED"],
	["Kila mtoto na koja lake.", "To every child his own neck ornament.", "UNPOSTED"],
	["Kila mwamba ngoma ,ngozi huivuta kwake.", "Anyone who streches a skin on a drum, pulls the skin down on his own side.", "UNPOSTED"],
	["Kila ndege huruka na mbawa zake.", "Every bird flies with its own wings.", "UNPOSTED"],
	["Kilio huanza mfiwa ndipo wa mbali wakaingia.", "The wailing begins for the deceased in order for those afar to join.", "UNPOSTED"],
	["Kimya kingi kina mshindo mkubwa.", "A long silence has a loud noise (mighty impact).", "UNPOSTED"],
	["Kinga na kinga ndipo moto uwakapo.", "One fire brand after another keeps fire burning.", "UNPOSTED"],
	["Kinyozi hajinyoi.", "A barber does not shave himself.", "UNPOSTED"],
	["Kinywa ni jumba la maneno.", "The mouth is a large room of words.", "UNPOSTED"],
	["Kipendacho moyo ni dawa.", "What the heart desires is medicine to it.", "UNPOSTED"],
	["Kipya kinyemi ingawa kidonda.", "A new thing is a source of joy even if it's a sore.", "UNPOSTED"],
	["Kisebusebu na roho kipapo.", "Refusing and wanting at the same time.??????????????", "UNPOSTED"],
	["Kisokula mlimwengu, sera nale.", "What is not eaten by man, let the devil eat it.", "UNPOSTED"],
	["Kitanda usichokilala hujui kunguni wake.", "You canot know what is in the bed on which you have not slept.", "UNPOSTED"],
	["Kivuli cha fimbo hakimfichi mtu jua.", "The shadow of a walking-stick cannot protect one from the sun.", "UNPOSTED"],
	["Kiwi cha yule ni chema chake hata ulimwengu uwishe.", "His blindness is his good fortune even to the end of the world.", "UNPOSTED"],
	["Kizuri chajiuza kibaya chajitembeza.", "A good thing sells itself a bad one treads on itself.", "UNPOSTED"],
	["Konzo ya maji haifumbatiki.", "A handful of water can not be grasped.", "UNPOSTED"],
	["Kosa moja haliachi mke.", "One woman's mistake never leaves her. (One fault does not warrant divorce of a wife)????????.", "UNPOSTED"],
	["Kozi mwandada, kulala na njaa kupenda.", "If a Goshawk sleeps hungry it's his own choice.", "UNPOSTED"],
	["Kuambizana kuko kusikilizana hapana.", "Those discussions lead to no agreements.", "UNPOSTED"],
	["Kucha M'ngu si kilemba cheupe.", "The fear of God is not wearing a white turban.", "UNPOSTED"],
	["Kuchamba kwingi, kuondoka na mavi.", "A lot of farting results in crap.", "UNPOSTED"],
	["Kufa kufaana.", "Death has its advantages too. It benefits those who inherit.", "UNPOSTED"],
	["Kufa kwa jamaa, harusi.", "The result of the death of a relative is a wedding. (Compared to a death of a relative).", "UNPOSTED"],
	["Kufa kwa mdomo, mate hutawanyika.", "When the mouth dies, it produces spittle. (When the head of the family dies, that family breaks up).", "UNPOSTED"],
	["Kuishi kwingi ni kuona mengi.", "To live long is to see much.", "UNPOSTED"],
	["Kujikwa si kuanguka, bali ni kwenda mbele.", "To stumble is not to fall but it is to go forward.", "UNPOSTED"],
	["Kukopa harusi kulipa matanga.", "Borrowing is like a wedding, repaying is like mourning.", "UNPOSTED"],
	["Kuku havunji yai lake.", "A hen does not break her own eggs.", "UNPOSTED"],
	["Kuku mgeni hakosi kamba mguuni.", "A new fowl always has string around it's legs.", "UNPOSTED"],
	["Kula kutamu, kulima mavune.", "Eating is sweet , digging is weary.", "UNPOSTED"],
	["Kulea mimba si kazi, kazi kulea mwana.", "It is not hard to nurse a pregnency, but it is hard to rear child.", "UNPOSTED"],
	["Kunako matanga kume kufa mtu.", "Where there is mourning someone has died.", "UNPOSTED"],
	["Kunguru mwoga hukimbiza mbawa zake.", "The timid crow withdraws his wings from harm.", "UNPOSTED"],
	["Kupanda mchongoma, kushuka ndio ngoma.", "You may climb a thorny hedge shrub, but when you come down it is a celebration. (To say something you may find hard to take back later or the journey may be difficult but arrival is celebration)", "UNPOSTED"],
	["Kupoteya njia ndiyo kujua njia.", "To get lost is to learn the way.", "UNPOSTED"],
	["Kutoa ni moyo usambe ni utajiri.", "Charity is the matter of the heart resulting in wealth.", "UNPOSTED"],
	["Kutu kuu ni la mgeni.", "Old rust is for the stranger.", "UNPOSTED"],
	["Kuzima koleo si mwisho wa uhunzi.", "Cooling the tongs is not end of forging(job).", "UNPOSTED"],
	["Kwa mwoga huenda kicheko na kwa shujaa huenda kilio.", "To the timid or coward - laughter, to the brave - praise.", "UNPOSTED"],
	["Kweli iliyo uchungu si uwongo ulio mtamu.", "The unpleasant or painful truth is better than a pleasing lie.", "UNPOSTED"],
	["Kwenda mbio siyo kufika.", "To go quickly is not neccessarily to arrive.", "UNPOSTED"],
	["Kwenye miti hakuna wajenzi.", "Where there are trees, there are no builders.", "UNPOSTED"],
	["La kuvunda(kuvunja) halina rubani.", "A vessel running aground has no captain.", "UNPOSTED"],
	["La kuvunda (kuvunja)halina ubani.", "There is no incence for something rotting.", "UNPOSTED"],
	["Lake mtu halimtapishi bali humchefusha.", "One's foul smell does not sicken him but makes him dirty (disgusts others).", "UNPOSTED"],
	["Leo ni leo asemayo kesho ni mwongo.", "Today is it and anyone who says it's tomorrow is lying. (Deal with what is happening now and anyone who is trying to delay it till tomorrow is a liar).", "UNPOSTED"],
	["Liandikwalo ndiyo liwalo.", "That which is written is the way it was(is).", "UNPOSTED"],
	["Lila na fila hazitangamani.", "Perhaps(good) and actuality(evil) are not compatable.", "UNPOSTED"],
	["Lipitalo, hupishwa .", "That which we have is cooked.", "UNPOSTED"],
	["Lisemwalo lipo, ikiwa halipo laja.", "That which is under discussion is real, and if it hasn't happened it's on it's way.", "UNPOSTED"],
	["Lisilokuwapo moyoni, halipo machoni.", "That which is not in the heart was not seen. (Out of sight out of mind)", "UNPOSTED"],
	["Lisilo na mkoma, hujikoma lilo.", "What has no end, will end itself.", "UNPOSTED"],
	["Maafuu hapatilizwi.", "You dont take vengeance on silliness.", "UNPOSTED"],
	["Macho hayana pazia.", "Eyes have no screens or shades. (They see all that is within view)", "UNPOSTED"],
	["Mafahali wawili hawakai zizi moja.", "Two bulls do not live in the same pasture.", "UNPOSTED"],
	["Maiti haulizwi sanda.", "The dead are not asked for their shrouds.", "UNPOSTED"],
	["Maji hufuata mkondo.", "Water follows the current. (Swim with the current)", "UNPOSTED"],
	["Maji huteremka bondeni hayapandi mlima.", "Water flows down the valleyit does not climb the hill.", "UNPOSTED"],
	["Maji ukiyavuliya nguo huna budi kuyaogelea.", "You do not have to bathe in the water in which you wash your clothes.", "UNPOSTED"],
	["Maji usiyoyafika hujui wingi wake.", "You do not know the size of the waters until you have seen them.", "UNPOSTED"],
	["Maji ya kifufu ni bahari ya chungu.", "A coconut's water is like an ocean to an ant.", "UNPOSTED"],
	["Maji yakija hupwa.", "When the tide rises, it will fall.", "UNPOSTED"],
	["Maji yaliyomwagika hayazoleki.", "The water which has spilt on him, cannot be gathered.", "UNPOSTED"],
	["Majumba makubwa husitiri mambo.", "Big houses conceal a lot.", "UNPOSTED"],
	["Majuto ni mjukuu.", "Regrets are like grandchildren. (They are few and far between)", "UNPOSTED"],
	["Mali ya bahili huliwa na wadudu.", "A miser's possessions are eaten by insects.", "UNPOSTED"],
	["Manahodha wengi chombo huenda mrama.", "With many captains, the ship does not sail astray. (Too many cooks spoil the broth)", "UNPOSTED"],
	["Maneno makali hayavunji mfupa.", "Harsh words do not break a bone.", "UNPOSTED"],
	["Maneno mema hutowa nyoka pangoni.", "Pleasent words will draw the snake from its hole.", "UNPOSTED"],
	["Masikini akipata matako hulia mbwata.", "When a poor man gets the ass of a carcase he boasts of his new good fortune.", "UNPOSTED"],
	["Masikini haokoti, akiokota huambiwa kaiba.", "A poor man does gather things, if he does he is told he stole them.", "UNPOSTED"],
	["Masikini na mwanawe tajiri na mali yake.", "To a poor man his child and to a rich man his wealth.", "UNPOSTED"],
	["Mavi usioyala, wayawingiani kuku?", " Dung which isn't eaten, will be eaten by the hens. (Why drive away fowls from the dung you do not eat yourself?)", "UNPOSTED"],
	["Mavi ya kale hayanuki.", "Old droppings do not stink.", "UNPOSTED"],
	["Mbinu hufuata mwendo.", "A double jointed arm moves in one motion. (Like father like son)", "UNPOSTED"],
	["Mbio za sakafuni huishia ukingoni.", "Running on the roof finishes at the edge.", "UNPOSTED"],
	["Mbiu ya mgambo ikilia ina jambo.", "When an buffalo-horn sounds, there is something of importance.", "UNPOSTED"],
	["Mchagua jembe si mkulima.", "One who selects a hoe is not necessarily a real farmer.", "UNPOSTED"],
	["Mchagua nazi, hupata koroma.", "He who selects coconuts with great care, still (ends up with) finds (unripe) ones just becoming ripe.", "UNPOSTED"],
	["Mchakacho ujao, halulengwi na jiwe.", "When there is a sudden noise you do not immediately throw a stone at it.", "UNPOSTED"],
	["Mchama ago hanyeli, huenda akauya papo.", "A traveller does not make a mess where he had made a camp as he might one day come back.", "UNPOSTED"],
	["Mchelea mwana kulia hulia yeye.", "He who fears the crying of a child, will cry himself.", "UNPOSTED"],
	["Mchele moja mapishi mengi.", "Rice is rice but they are many ways of cooking it.", "UNPOSTED"],
	["Mcheka kilema hafi bila kumpata.", "He who laughs at a cripple will not die without becoming one himself.", "UNPOSTED"],
	["Mcheza hawi kiwete, ngoma yataka matao.", "A dancer will not become crippled as long as the dance needs him.", "UNPOSTED"],
	["Mcheza kwao hutuzwa.", "He who dances at home will be rewarded.", "UNPOSTED"],
	["Mcheza na tope humrukia.", "He who plays with mud will get splashed.", "UNPOSTED"],
	["Mchezea zuri, baya humfika.", "He who ridicules the good will be overtaken by evil.", "UNPOSTED"],
	["Mchimba kisima hungia mwenyewe.", "He who digs a well will also enter it himself.", "UNPOSTED"],
	["Mchonga mwiko hukimbiza mkono wake.", "The maker of wooden spoons makes quick work of it.", "UNPOSTED"],
	["Mchovya asali hachovi mara moja.", "He who dips his finger into honey does not dip it once.", "UNPOSTED"],
	["Mchuma janga hula na wakwao.", "He who earns calamity, eats it with his family.", "UNPOSTED"],
	["Mchumia juani hula kivulini.", "He who earns his living in the sun, eats in the shade.", "UNPOSTED"],
	["Mdharau biu hubiuka yeye.", "He who hates (ridicules) a deformed person will become deformed himself.", "UNPOSTED"],
	["Meno ya mbwa hayaumani.", "The teeth of a dog do not hurt each other. I.e brothers do not harm one another when they fight.", "UNPOSTED"],
	["Mfa maji hukamata majii.", "A drowning man claws at the water.", "UNPOSTED"],
	["Mficha uchi hazai.", "One who hides private parts does not bear children.", "UNPOSTED"],
	["Mfinyazi hulia gaeni.", "A potter eats from a potsherd.", "UNPOSTED"],
	["Mfuata nyuki hakosi asali.", "One who follows bees will never fail to get honey.", "UNPOSTED"],
	["Mfukuzwa kwao hana pakwenda.", "He who is expelled from home has no where to go.", "UNPOSTED"],
	["Mgaagaa na upwa hali wali mkavu.", "A lazy person living near the shore does not eat only rice.", "UNPOSTED"],
	["Mganga hajigangui.", "A doctor does not cure himself.", "UNPOSTED"],
	["Mgema akisifiwa tembo hulitia maji.", "If the palm-wine tapper is praised for his wine, he dilutes it with water.", "UNPOSTED"],
	["Mgeni ni kuku mweupe.", "A stranger is like a white fowl (noticeble)", "UNPOSTED"],
	["Mgeni njoo mwenyeji apone.", "Let the guest come so that the host may benifit.", "UNPOSTED"],
	["Mgonjwa haulizwi uji.", "A sick person is not asked for porridge.", "UNPOSTED"],
	["Miye nyumba ya udongo, sihimili vishindo.", "I am a mud hut, I cannot stand shocks.", "UNPOSTED"],
	["Mjinga akierevuka mwerevu yupo mashakani.", "If a fool becomes enlightened, the wise man is in the sticks(trouble).", "UNPOSTED"],
	["Mjumbe hauawi.", "The messenger is not killed.", "UNPOSTED"],
	["Mkamatwa na ngozi ndiye mwizi.", "The one who is caught with the skin is the thief.", "UNPOSTED"],
	["Mkamia maji hayanywi.", "He who squeezes out all the water will have nothing to drink.", "UNPOSTED"],
	["Mkata (masikini) hana kinyongo.", "A poor man has no contempt.", "UNPOSTED"],
	["Mke ni nguo, mgomba kupalilia.", "A wife needs (new) clothes evidenced by digging around the banana plant. (otherwise she becomes quarrelsome).", "UNPOSTED"],
	["Mkono moja hauchinji ngombe.", "One hand can not slaughter a cow.", "UNPOSTED"],
	["Mkono moja haulei mwana.", "A single hand cannot bring up a child.", "UNPOSTED"],
	["Mkono mtupu haulambwi.", "An empty hand is not licked.", "UNPOSTED"],
	["Mkono usioweza kuukata, ubusu.", "Kiss the hand which cannot cut you.", "UNPOSTED"],
	["Mkosa kitoweo humangiria.", "One who has no gravy eats sparingly.", "UNPOSTED"],
	["Mkuki kwa nguruwe mtamu, kwa mwanadamu uchungu.", "To spear a pig is tasty, but to spear a person is painful.", "UNPOSTED"],
	["Mkulima ni mmoja walaji ni wengi.", "The farmer is one but those who eat the fruits of his labour are many.", "UNPOSTED"],
	["Mla cha mwenziwe na chake huliwa.", "He who eats another's food will have his own food eaten by others.", "UNPOSTED"],
	["Mla cha uchungu na tamu hakosi.", "He who eats bitter and sweet things does not go without.", "UNPOSTED"],
	["Mlaji ni mla leo; mla jana ni kalani?", " The diner is the one who eats today(eat what you have today); yesterday's diner, (what was eaten yesterday)is of the past.", "UNPOSTED"],
	["Mla kuku wa mwenziwe miguu humwelekeya.", "He who eats his neighbour's chicken will be discovered by his footprints.", "UNPOSTED"],
	["Mla mbuzi hulipa ngombe.", "The goat eater repays with a cow.", "UNPOSTED"],
	["Mla mla leo mla jana kala nini?", " Eat up today, after all what did yesterday's diner eat?", "UNPOSTED"],
	["Mla nawe hafi nawe ila mzaliwa nawe.", "He who eats with you will not die with you only he who was born with you.", "UNPOSTED"],
	["Mlenga jiwe kundini hajui limpataye.", "He who who throws a stone in a crowd does not know whom it hits.", "UNPOSTED"],
	["Mlimbua nchi ni mwananchi.", "He who enjoys the first fruits of a country is a son of that country.", "UNPOSTED"],
	["Mnyamaa kadumbu.", "One who keeps silent, endures.", "UNPOSTED"],
	["Mnywa maji kwa mkono moja, Kiu yake i pale pale.", "He who drinks water with one hand remains thirsty.", "UNPOSTED"],
	["Moto hauzai moto.", "Fire does not beget fire. (In the end it produces ashes)", "UNPOSTED"],
	["Mpanda farasi wawili hupasuka msamba.", "One who rides two horses at once will split apart.", "UNPOSTED"],
	["Mpanda ngazi hushuka.", "He who climbs a ladder will descend it. (What goes up must come down)", "UNPOSTED"],
	["Mpanda ovyo hula ovyo.", "He who sows haphazardly, will eat likewise.", "UNPOSTED"],
	["Mpemba akipata gogo hanyii chini.", "If a native of Pemba can find a log he does not relieve himself on the ground. (Nothing but the best)", "UNPOSTED"],
	["Mpemba hakimbii mvua ndogo.", "A native of Pemba does not run away from a small shower.", "UNPOSTED"],
	["Mpenzi hana kinyongo.", "A lover has no scruples(faults).", "UNPOSTED"],
	["Mpiga ngumi ukuta huumiza mkonowe.", "He who fights with a wall will only hurt his hand.", "UNPOSTED"],
	["Mpofuka ukongweni,hapotewi na njia.", "He who becomes blind in his old age does not lose his way.", "UNPOSTED"],
	["Msafiri masikini ajapokuwa sultani.", "A traveller is poor, though he be a sultan (ruler).", "UNPOSTED"],
	["Msasi haogopi mwiba.", "A hunter is not afraid of a thorn.", "UNPOSTED"],
	["Msema pweke hakosi.", "One who talks to himself cannot be wrong. (no one to correct him)", "UNPOSTED"],
	["Mshale kwenda msituni haukupotea.", "If an arrow goes into a forest it is not lost.", "UNPOSTED"],
	["Mshoni hachagui nguo.", "A tailor does not select the clothing.", "UNPOSTED"],
	["Msitukane wagema na ulevi ungalipo.", "Do not abuse palm-wine tappers before you are drunk.", "UNPOSTED"],
	["Msitukane wakunga na uzazi ungalipo.", "Do not abuse midwives while child-bearing continues.", "UNPOSTED"],
	["Mstahimilivu hula mbivu.", "A patient man will eat ripe fruits.", "UNPOSTED"],
	["Mtaka cha mvunguni sharti ainame.", "He who requires what is under the bed must bend for it.", "UNPOSTED"],
	["Mtaka nyingi nasaba hupata mwingi msiba.", "He who asks much of his relatives brings plenty of trouble upon himself.", "UNPOSTED"],
	["Mtaka unda haneni.", "He who wants to make something does not talk. (His intentions are not announced, just turns them into actions)", "UNPOSTED"],
	["Mtaka yote hukosa yote.", "He who desires all, will get nothing.", "UNPOSTED"],
	["Mtaka yote kwa pupa, hukosa yote.", "He who wants everything in a hurry, loses everything.", "UNPOSTED"],
	["Mtegemea nundu haachi kunona.", "He who relies on a cows hump will not fail to grow fat.", "UNPOSTED"],
	["Mtembezi hula miguu yake.", "An aimless wanderer wears away his legs.", "UNPOSTED"],
	["Mteuzi hashi tamaa.", "A connoisseur never stops desiring.", "UNPOSTED"],
	["Mti hauwendi ila kwa nyenzo.", "A log cannot move save by the help of rollers.", "UNPOSTED"],
	["Mtondoo haufi maji.", "A musket does not die in water.", "UNPOSTED"],
	["Mtoto akililia wembe mpe.", "If a child cries for a razor give it him. (Let him learn by experience)", "UNPOSTED"],
	["Mtoto umleyavyo ndivyo akuavyo.", "As a child is reared, so he will become.", "UNPOSTED"],
	["Mtoto wa nyoka ni nyoka.", "The child of a snake is a snake.", "UNPOSTED"],
	["Mtu aliyeumwa na nyoka akiona ung'ongo hushtuka.", "One who was bitten by a snake is startled even if he sees a strip of a palm leaf. i.e. Once bitten twice shy.", "UNPOSTED"],
	["Mtu hakatai mwito hukataa aitwalo.", "A person does not object to being called, he objects to what he is called for.", "UNPOSTED"],
	["Mtu hujikuna ajipatiapo.", "A person scratches himself where his hand can reach.", "UNPOSTED"],
	["Mtu huulizwa amevaani haulizwi amekulani.", "A person is asked about his clothing not what he has eaten.", "UNPOSTED"],
	["Mtumai cha ndugu hufa masikini.", "One who always depends on his brother will die poor.", "UNPOSTED"],
	["Mtumi wa kunga haambiwi maana.", "The carrier of a secret message is not told its meaning.", "UNPOSTED"],
	["Mtumikie kafiri upate mradi wako.", "Serve even an unbeliever to attain your own ends.", "UNPOSTED"],
	["Mtupa jongoo hutupa na mti wake.", "If you throw away a millipede you should throw away the stick you picked it up with", "UNPOSTED"],
	["Mume wa mama ni baba.", "A husband of a mother is a father", "UNPOSTED"],
	["Mungu hamfichi mnafiki.", "God does not conceal a liar(hypocrite).", "UNPOSTED"],
	["Mvumbika changa hula mbovu.", "One who stores half grown(ripe) fruit eats it rotten.", "UNPOSTED"],
	["Mvungu mkeka.", "The space under the bed is like a mat. (You can see right through him)", "UNPOSTED"],
	["Mvunja nchi ni mwananchi.", "The destroyer of a country is a citizen of that country.", "UNPOSTED"],
	["Mvuvi ajuwa pweza alipo.", "A fisheman knows where to look for an octopus.", "UNPOSTED"],
	["Mwacha asili ni mtumwa.", "He who renounces his ancestry is a slave.", "UNPOSTED"],
	["Mwamba na wako hukutuma umwambiye.", "He who speaks ill of another in your presence sends you to tell that other person.", "UNPOSTED"],
	["Mwamini Mungu si mtovu.", "He who trusts in God lacks nothing.", "UNPOSTED"],
	["Mwana maji wa Kwale kufa maji mazowea.", "To a sailor from Kwale, death by water is a common experience.", "UNPOSTED"],
	["Mwana mkaidi hafaidi mpaka siku ya idi.", "An obstinate child does not suffer save on the day Idd.", "UNPOSTED"],
	["Mwana mkuwa nawe ni mwenzio kama wewe.", "The child who grows up with you is your friend.", "UNPOSTED"],
	["Mwana simba ni simba.", "The child of lion is a lion.", "UNPOSTED"],
	["Mwana wa kuku hafunzwi kuchakura.", "A chick is not taught how to scratch up the ground.", "UNPOSTED"],
	["Mwana wa mtu ni kizushi; akizuka, zuka naye.", "A child is a revolutionist; where he wanders watch him.", "UNPOSTED"],
	["Mwanga mpe mtoto kulea.", "Give a child to an educated person to rear.", "UNPOSTED"],
	["Mwangaza mbili moja humponyoka.", "Given 2 clear choices, one will surely escape him", "UNPOSTED"],
	["Mwanzo kokochi mwisho nazi.", "The begining is a bud and the end is a coconut.", "UNPOSTED"],
	["Mwanzo wa chanzo ni chane mbili.", "The beginning of a mat-making is two slips of raffia leaf.", "UNPOSTED"],
	["Mwanzo wa ngoma ni lele.", "The sign of the start of a dance is \"lele\". (One voice will be joined by others)", "UNPOSTED"],
	["Mwapiza la nje hupata la ndani.", "One who curses someone in public, brings it on himself in private.", "UNPOSTED"],
	["Mwekaji kisasi haambiwi mwerevu.", "He who nurses vegeance is not called wise.", "UNPOSTED"],
	["Mwenda bure si mkaa bure huenda akaokota.", "One who walks with no reason is not like one who sits without reason,the one who walks might pick up something.", "UNPOSTED"],
	["Mwenda mbio hujikwa kidole.", "A person who is in too much of a hurry stubs his toe.", "UNPOSTED"],
	["Mwenda omo na tezi marejeo ngamani.", "He who goes from bow to stern must return to the hold(bilge).", "UNPOSTED"],
	["Mwenye kelele hana neno.", "A noisy person has nothing to say", "UNPOSTED"],
	["Mwenye kovu usidhani kapowa.", "Do not think one with a scar is healed.", "UNPOSTED"],
	["Mwenye kubebwa hujikaza.", "He who is carried must cling on.", "UNPOSTED"],
	["Mwenye kuchinja hachelei kuchuna.", "He who slaughters does not hesitate skinning it.", "UNPOSTED"],
	["Mwenye kuumwa na nyoka akiona jani hushtuka.", "If one has been bitten by a snake, when he sees a long piece of grass he is frightened. (Once bitten twice shy)", "UNPOSTED"],
	["Macho haambiwi tazama.", "One who has eyes does not need to be told to look.", "UNPOSTED"],
	["Mwenye nguvu mpishe.", "Let a strong man pass", "UNPOSTED"],
	["Mwenye njaa hana miiko.", "A hungry man does not have any foods he chooses not to eat(observes no taboos).", "UNPOSTED"],
	["Mwenye pupa hadiriki kula tamu.", "A hasty person misses the sweet things. (He cannot wait for the fruit to ripen)", "UNPOSTED"],
	["Mwenye shibe hamjui mwenye njaa.", "A satisfied person does not know how a hungry man feels. (He that is warm thinks all are warm)", "UNPOSTED"],
	["Mwenye shoka hakosi kuni.", "An axeman does not lack firewood.", "UNPOSTED"],
	["Mwenye tumbo ni tumbole, angafunga mkaja.", "She who is pregnant is pregnant, even though she wraps herself in an 'mkaja'.[Mkaja is the cloth a woman wears round her stomach after giving birth]. (You don't achieve something by pretending you have achieved it.)", "UNPOSTED"],
	["Mwenzako akinyolewa wewe tia maji.", "If your friend is shaving put water on your face. (When you see a neighbouring country being invaded, prepare to face the same situation yourself. When your neighbour's house is on fire, take care of your own house)", "UNPOSTED"],
	["Mwibaji na watwana, mlifi ni mwungwana.", "A thief is a rogue, but the one who repays is a gentleman.", "UNPOSTED"],
	["Mwili wa mwenzio ni kando ya mwilio.", "Your companion's body is beside(not a part of) your body.", "UNPOSTED"],
	["Mwizi hushikwa na mwizi mwenziwe.", "A thief is caught by his fellow thief. (Set a thief to catch a thief)", "UNPOSTED"],
	["Mwomba chumvi huombea chunguche.", "He who asks for salt does so for his own cooking pot.", "UNPOSTED"],
	["Mwosha hadhuru maiti.", "The washer of corpses does no harm to the dead.", "UNPOSTED"],
	["Mwosha huoshwa.", "The corpse-washer is washed (in his turn). (Tit for tat)", "UNPOSTED"],
	["Mwosha husitiri maiti.", "The washer conceals the corpse (gives nothing away).", "UNPOSTED"],
	["Mzaha,mzaha, hutumbuka usaha.", "Joke, joke, discharges pus (i.e. do not dismiss even a small scratch as if it were only a joke-it may go bad) A stitch in time saves nine.", "UNPOSTED"],
	["Mzazi haachi ujusi.", "A mother who has just given birth cannot avoid her predicament(ritual defilement).", "UNPOSTED"],
	["Mzigo Wa mwenzio ni kanda Ia usufi.", "Your companion's burden is (no more than) a light load (to you). (The burden is light on the shoulder of another)", "UNPOSTED"],
	["Mzika pembe ndiye mzua pembe.", "The one who buries(hides) ivory is the one to dig it up.", "UNPOSTED"],
	["Mzowea kutwaa, kutoa ni vita.", "He who is accustomed to taking, giving is a battle.", "UNPOSTED"],
	["Mzowea kunyonga, kuchinja hawezi.", "He who strangles cannot slaughter.", "UNPOSTED"],
	["Mzungu wa kula hafundishwi mwana.", "The process of eating is not taught to a child.", "UNPOSTED"],
	["Nahodha wengi, chombo huenda mrama.", "Too many captains and the ship rolls. (Too many cooks spoil the broth)", "UNPOSTED"],
	["Natuone ndipo twambie, kusikia si kuona.", "Let us see then tell; hearing is not seeing. (Seeing is believing)", "UNPOSTED"],
	["Nazi mbovu harabu ya nzima.", "A rotten coconut spoils the good ones(A rotten apple spoils the whole bushel. A sickly sheep infects the whole flock).", "UNPOSTED"],
	["Ndege mjanja hunaswa na tundu bovu.", "A mischievious bird can be trapped in a rotten cage.", "UNPOSTED"],
	["Ndege mwigo hana mazowea.", "A bird that imitates others has no individual personality.", "UNPOSTED"],
	["Ndugu chungu, jirani mkungu.", "A brother is (as useful as) a cooking pot and a neighbour is (as useful as) a cooking pot lid.", "UNPOSTED"],
	["Ndugu mwui afadhali kuwa naye.", "A bad brother is far better than no brother. Cf. Blood is thicker than water.", "UNPOSTED"],
	["Ndugu wakigombana, chukua jembe ukalime, wakipatana chukua kikapu ukavune.", "When brothers quarrel, take a hoe and go and dig and when they make up take a basket and harvest the crop. (never interfere with a dispute between brothers)", "UNPOSTED"],
	["Ngoja, ngoja huumiza matumbo.", "Waiting hurts the stomach.", "UNPOSTED"],
	["Ngoma ikilia sana, haikawii kupasuka.", "If a drum sounds loud, it will soon burst.", "UNPOSTED"],
	["Ngoma ivumayo haidumu.", "A noisy drumming does not last long.", "UNPOSTED"],
	["Ngoma ivumayo haikawii kupasuka.", "A drum that is sounded loudly will soon split. (A pitcher that often goes to the well, is broken at last)", "UNPOSTED"],
	["Ngozi ivute ili maji.", "Stretch the hide while it still has water(is green). (Strike while the iron is hot)", "UNPOSTED"],
	["Nguruwe aendealo, ndilo atendalo.", "Where a pig goes, that is where it does it's thing.", "UNPOSTED"],
	["Nia njema ni tabibu, nia mbaya huharibu.", "A good purpose is healthy (it heals or keeps you well) and an evil purpose corrupts or destroys.", "UNPOSTED"],
	["Nifae na mvua nikufae na jua.", "Do me a favour during a rainy season and I shall do the same to you during the dry season.", "UNPOSTED"],
	["Nimekula asali udogoni, utamu ungali gegoni.", "I ate honey in my childhood, and its sweetness is still in my tooth.", "UNPOSTED"],
	["Nimekupaka wanja, wewe wanipaka pilipili.", "I anointed you with perfume now you, in return, anoint me with pepper", "UNPOSTED"],
	["Njema haziozi.", "Good does not go bad.", "UNPOSTED"],
	["Njia mbili zilimshinda mzee fisi, alipasuka msamba.", "The two paths(ways) overcame the old hyena, and split him in two.", "UNPOSTED"],
	["Njia ya mwongo fupi.", "The way of a liar is short. (He soon comes to grief).", "UNPOSTED"],
	["Njia ya siku zote haina alama.", "A long path has no signpost. (A used key is always bright.", "UNPOSTED"],
	["Ng'ombe avunjikapo guu hurejea zizini.", "When a bull breaks his leg, he is sure to go back to his pasture.", "UNPOSTED"],
	["Ng'ombe haelemewi na nunduye.", "A cow is not oppressed by it's own hump.", "UNPOSTED"],
	["Nta si asali nalikuwa nazo si uchunga.", "Wax is not honey; though I had them I did not keep them.", "UNPOSTED"],
	["Nyani haoni kundule, huliona la mwenziwe.", "The ape does not see his own backside, he only sees his companion's.", "UNPOSTED"],
	["Nyimbo ya kufunzwa haikeshi ngoma.", " (Foreign) Songs which need to be taught do not last at a traditional dance", "UNPOSTED"],
	["Nyuki huenda na maua yake.", "A bee are found in flowers.", "UNPOSTED"],
	["Nyumba usiyolala ndani huijui ila yake.", "You cannot know the defects of a house you have not slept in. (It is the wearer who knows where the shoe pinches)", "UNPOSTED"],
	["Nyumba ya udongo haihimili vishindo.", "A mud hut cannot withstand great shocks.", "UNPOSTED"],
	["Nzi kufa juu ya kidonda si haramu.", "For a fly to die on an ulcer is not bad (after all, he got what he wanted).", "UNPOSTED"],
	["Pabaya pako si pema pa mwenzako.", "Your bad situation is no better (so far as you are concerned) than your colleague's (which will do you no good).", "UNPOSTED"],
	["Padogo pako si pakubwa pa mwenzako.", "Though a small thing to you, it is no big deal to your colleague.", "UNPOSTED"],
	["Painamapo ndipo painukapo.", "Where it bends down is where it raises up.", "UNPOSTED"],
	["Paka akiondoka, panya hutawala.", "When the cat goes away, the mice reign. (When the cat's away, the mice do play)", "UNPOSTED"],
	["Paka hakubali kulala chali.", "A cat can never he made to lie on its back.", "UNPOSTED"],
	["Paka wa nyumba haingwa.", "A cat belonging to the house is not chased away.", "UNPOSTED"],
	["Panapo wengi hapaharibiki neno.", "Where there are many, nothing goes wrong. (A council of many people ensures that things are kept in line.)", "UNPOSTED"],
	["Papo kwa papo kamba hukata jiwe.", "Constant rubbing of a rope will cut a stone. Constant dripping wears away a stone.", "UNPOSTED"],
	["Pele hupewa msi kucha.", "Scabies are given to him who has no fingernails. (who cannot scratch himself).", "UNPOSTED"],
	["Pema usijapo pema; ukipema si pema tena.", "It is a good place if you don't go too often otherwise it is no longer good. (Familiarity brings contempt.", "UNPOSTED"],
	["Do not outstay one's welcome)", "Penye kuku wengi, hapamwagwi mtama.", "UNPOSTED"],
	["Where there are many fowls, millet is not spilled. ( It is not advisable to disclose a secret in the presence", "of a number of people).", "UNPOSTED"],
	["Penye mafundi, hapakosi wanafunzi.", "Where there are experts there will be no lack of learners.", "UNPOSTED"],
	["Penye mbaya wako, hapakosi mwema wako/na mwema wako hakosi.", "Where there is ill fortune, there is also good fortune.", "UNPOSTED"],
	["Penye miti hakuna wajenzi.", "Where there are plenty of trees there are no builders.", "UNPOSTED"],
	["Penye nia ipo njia.", "Where there's a will there's a way.", "UNPOSTED"],
	["Penye urembo ndipo penye urimbo.", "Where there is finery/beauty, there also lies the snare (Lit: birdlime).", "UNPOSTED"],
	["Penye wazee haliharibiki neno.", "Where there are old(wise) people, nothing can go wrong.", "UNPOSTED"],
	["Penye wengi pana mengi.", "Where there are many (present) there is much (said).", "UNPOSTED"],
	["Penye wengi pana Mungu.", "Where there are many people, there is God.", "UNPOSTED"],
	["Penye wimbi na mlango ni papo.", "The breakers(danger) and the channel(safety) are close together.", "UNPOSTED"],
	["Pilipili usozila zakuwashiani?", " How can you be burnt by chilies which you have not eaten?", "UNPOSTED"],
	["Pofu hasahau mkongoja wake.", "A blind person does not forget his walking stick.", "UNPOSTED"],
	["Pwagu hupata pwaguzi.", "A thief finds another one (who is a bigger and better thief than he is).", "UNPOSTED"],
	["Radhi ni bora kuliko mali.", "Blessings are better than wealth.", "UNPOSTED"],
	["Sahani iliyofunikwa, kilichomo kimesitirika.", "When a plate is covered, its contents are hidden.", "UNPOSTED"],
	["Samaki mmoja akioza, huoza wote.", "If one fish rots, they all rot. Cf. A rotten apple spoils its neighbours.", "UNPOSTED"],
	["Shika! Shika! na mwenyewe nyuma.", "Hold him! Hold him! and you yourself after him (i.e. you shouldn't expect others to do all the work).", "UNPOSTED"],
	["Shimo Ia ulimi mkono haufutiki.", "A pit of (dug by) the tongue cannot be covered up by the hand (words are more dangerous). (What has been done cannot be reversed)", "UNPOSTED"],
	["Shoka lisilo mpini halichanji kuni.", "An axe with no handle does not split firewood.", "UNPOSTED"],
	["Si kila mwenye makucha huwa simba.", "Not all that have claws are lions.", "UNPOSTED"],
	["Sikio halilali na njaa.", "An ear does not go to bed hungry (there's always plenty of gossip).", "UNPOSTED"],
	["Sikio halipwani kichwa/Sikio halipiti kichwa.", "The ear is not greater than the head.", "UNPOSTED"],
	["Sikio Ia kufa halisikii dawa.", "A dying ear does not feel the medicine.", "UNPOSTED"],
	["Siku njema huonekana asubuhi.", "A good day becomes evident in the morning.", "UNPOSTED"],
	["Siku utakayokwenda uchi, ndiyo siku utakayokutana na mkweo.", "The day you go naked, is the day you will meet your father/mother-in-law.", "UNPOSTED"],
	["Simba mwenda kimya ndiye mla nyama.", "The lion which moves silently is the one that eats meat.", "UNPOSTED"],
	[" Simbiko haisimbuki ila kwa msukosuko.", "A thing that is firmly fixed cannot be dislodged except with much trouble.", "UNPOSTED"],
	["Sitafuga ndwele na waganga tele.", "I shall not suffer illness while doctors abound.", "UNPOSTED"],
	["Subira ni ufunguo wa faraja.", "Patience is the key to tranquility.", "UNPOSTED"],
	["Subira yavuta heri huleta kilicho mbali.", "Patience attracts happiness; it brings near that which is far.", "UNPOSTED"],
	["Sumu ya neno ni neno.", "The poison for a word is a word. Tit for tat.", "UNPOSTED"],
	["Tamaa mbele, mauti nyuma.", "Place desire first, death will follow.", "UNPOSTED"],
	["Taratibu ndiyo mwendo.", "Carefully is the way to go. Go carefully, go surely.", "UNPOSTED"],
	["Teke Ia kuku halimwumizi mwanawe.", "A hen's kick does not hurt her chick.", "UNPOSTED"],
	["Tonga si tuwi.", "The juice of an immature coconut Is not like the real coconut juice.", "UNPOSTED"],
	["Ucheshi wa mtoto ni anga la nyumba.", "The laughter of a child brightens the house.", "UNPOSTED"],
	["Uchungu wa mwana, aujua mzazi.", "The pain of a child is felt by the parent. The Iabour of childbirth is known only to the mother.", "UNPOSTED"],
	["Uchungu wa mtoto u katika nyonga ya mama yake.", "The pain(trouble with) of a child is on it's mother's hip.", "UNPOSTED"],
	["Udongo uwahi ungali maji.", "Work the clay while it is still wet. Strike while the iron is hot.", "UNPOSTED"],
	["Undugu wa nazi hukutania chunguni.", "The brotherhood of coconuts meet in the cooking pot (said of people who do not cooperate until it is too late).", "UNPOSTED"],
	["Ukienda kwa wenye chongo, vunja lako jicho.", "When you go among one-eyed people, put out your own eye. Cf. Where ignorance is bliss, it is folly to be wise. When in Rome, do as the Romans do.", "UNPOSTED"],
	["Ukiona kwako kunaungua kwa mwenzako kunateketea.", "If you find your own house is on fire, you may be sure that your neighbour's house is burning", "UNPOSTED"],
	["much more fiercely.", "Consider yourself lucky.", "UNPOSTED"],
	["Ukiona neno, usiposema neno, hutapatikana na neno.", "If you see something and say nothing, you will have nothing to suffer for. Cf. Mind your own business.", "UNPOSTED"],
	["Ukiona vinaelea, vimeundwa.", "If you see vessels afloat,(remember) that they have had to be built.", "UNPOSTED"],
	["Ukiona zinduna, ambari iko nyuma.", "If you see amber, ambergis is (not far) behind, (i.e. Where there is a jealous husband, there will be jealous wife). (Sauce for the goose.?)", "UNPOSTED"],
	["Ukipewa shibiri usichukue pima.", "If you are offered a span, do not take a couple of yards. Cf. Give him an inch and he will take an ell.", "UNPOSTED"],
	["Ukupigao ndio ukufunzao.", "What beats you is what teaches you. Cf. Spare the rod and spoil the child.", "UNPOSTED"],
	["Ukistaajabu ya Mussa utaona ya Firauni.", "If you are astonished at Moses' deeds, you will be even more astonished at Pharaoh's. Moses declared himself to be a prophet, but Pharaoh declared himself to be God.", "UNPOSTED"],
	["Ukitaja nyoka, shika fimbo mkononi.", "When you mention a snake, have a stick ready in your hand. Talk of the devil, and you'll hear the rustle of his wings.", "UNPOSTED"],
	["Ukitaka kula nguruwe, chagua aliyenona.", "If you want to eat pig, choose one which is fat. Cf. You might as well be hanged for a sheep as a lamb. (Muslims are forbidden pork).", "UNPOSTED"],
	["Ukitaka uzuri sharti udhurike.", "If you want beauty, you must (first) be injured.", "UNPOSTED"],
	["Ukuukuu wa kamba Si upya wa ukambaa.", "A well-worn coir-rope is better than a new rope made from raffia.", "UNPOSTED"],
	["Ulacho ndicho chako, kilichobaki nicha mchimba lindi.", "What you eat is yours, that which remains is the grave-digger's(heir).", "UNPOSTED"],
	["Ulimi hauna mfupa.", "A tongue has no bone(not stable or reliable).", "UNPOSTED"],
	["Ulimi unauma kuliko meno.", "The tongue hurts more than the teeth.", "UNPOSTED"],
	["Ulipendalo hupati hupata ujaliwalo.", "That which you desire you do not get, you get what is ordained to you (by God). Cf. Man proposes, God disposes.??", "UNPOSTED"],
	["Ulivyoligema utalinywa.", "As you tapped (palm-wine), so you will drink.", "UNPOSTED"],
	["As you sow, so shall you reap.", "You have made your bed now you must lie on it.", "UNPOSTED"],
	["Umejigeuza pweza, unajipalia makaa? Have you changed into a cuttle-fish in that you heap live embers on yourself?", "Umekuwa bata akili kwa watoto? Are you a duck in that your mind is with your children?", "UNPOSTED"],
	["Umekuwa jeta hubanduki?", "Are you a Jeta in that you do not move?", "UNPOSTED"],
	["Umekuwa nguva, huhimili kishindo?", "Are you a dugong in that you cannot bear a loud sound?", "UNPOSTED"],
	["Unamlaumu mwewe, kipanga yuwesha kuku.", "You are blaming the hawk, (while) the falcon is killing the chickens.", "UNPOSTED"],
	["Ungalijua alacho nyuki, usingalionja asali.", "Had you known what bees eat, you would not have tasted the honey.", "UNPOSTED"],
	["Ushikwapo shikamana.", "When you are seized, hold on.", "UNPOSTED"],
	["Usiache kunanua kwa kutega.", "Do not neglect the undoing (of a full trap) for the setting (of others). A bird in the hand is worth two in the bush.", "UNPOSTED"],
	["Usiache mbachao kwa msala upitao.", "Never give up your own old mat for a better prayer mat which you see passing. i.e. Don't desert your old friend for a new acquaintance who may not be permanent.", "UNPOSTED"],
	["Usicheze na simba, ukamtia mkono kinywani.", "Do not play with a lion, you might put your hand in it's mouth.", "UNPOSTED"],
	["Usidharau kiselema chalima kikapita jembe zima.", "Don't despise a worn hoe, it is able to cultivate and even surpass a sound one.", "UNPOSTED"],
	["Usigombe na mkwezi, nazi imeliwa na mwezi.", "Don't quarrel with the coconut-palm climber, the coconut has been eaten by the moon. (Don't bite the hand that feeds you)", "UNPOSTED"],
	["Usijifanye kuku mweupe.", "Do not pretend to be a white fowl (important person).", "UNPOSTED"],
	["Usikaange mbuyu ukawaachia wenye meno watafune.", "Do not roast baobab kernels and leave those who have teeth chewing (them). Don't start quarrels among other people with your rumours.", "UNPOSTED"],
	["Usile na kipofu ukamgusa mkono.", "Don't eat with the blind, you might touch his hand. (to do so will lead him to suspect that either the food is finished or you are trying to play a trick on him). You must be very careful with a 'simple' person lest you do something to make him suspicious of you.", "UNPOSTED"],
	["Usimwamshe aliyelala utalala wewe.", "Do not wake one who is sleeping, you too will sleep.", "UNPOSTED"],
	["Usinivishe kilemba cha ukoka.", "Do not put a grass turban on my head. Do not flatter me.", "UNPOSTED"],
	["Usipoziba ufa utajenga ukuta.", "If you do not fill a crack, you will have to build a wall.", "UNPOSTED"],
	["Usisafiriye na nyota ya mwenzio.", "Don't travel under another's lucky star. Do not rely on someone else's good fortune.", "UNPOSTED"],
	["Usisahau ubaharia kwa sababu ya unahodha.", "Do not forget what it is like to be a sailor when you are a captain yourself.", "UNPOSTED"],
	["Usishindane na Kari; Kari ni mja wa Mungu.", "Do not compete with Kari, Kari comes from God.", "UNPOSTED"],
	["Usitukane wagema na ulevi ungalipo.", "Speak no ill of palm-wine tappers as long as drinking persists.", "UNPOSTED"],
	["Usitukane wakunga na uzazi 'ungalipo.", "Speak no ill of midwives while childbirth still continues.", "UNPOSTED"],
	["Usiyavuke maji usiyoweza kuyaoga.", "Do not cross water that is too deep for wading.", "UNPOSTED"],
]

i = 0

# for methali in mamethali:
# 	mamethali2[i] = i
# 	i = i + 1
		
# print(mamethali2)

# from random import shuffle

# shuffled2 =[193, 260, 22, 7, 397, 362, 129, 20, 197, 139, 144, 108, 48, 238, 418, 92, 350, 90, 172, 367, 106, 112, 25, 55, 88, 402, 26, 277, 147, 6, 293, 192, 95, 119, 357, 431, 420, 151, 67, 176, 99, 47, 184, 341, 268, 219, 342, 291, 261, 369, 127, 259, 68, 303, 240, 237, 262, 340, 170, 148, 301, 394, 276, 376, 36, 380, 213, 128, 214, 248, 76, 246, 345, 428, 30, 304, 72, 89, 59, 74, 166, 390, 179, 309, 437, 183, 53, 355, 159, 212, 381, 267, 132, 434, 334, 100, 206, 410, 40, 215, 204, 58, 31, 211, 175, 69, 117, 245, 438, 427, 66, 299, 337, 65, 243, 230, 423, 18, 393, 208, 134, 368, 233, 52, 424, 387, 19, 232, 440, 407, 15, 300, 290, 416, 287, 43, 85, 44, 382, 1, 34, 388, 429, 75, 60, 120, 178, 21, 391, 414, 308, 249, 324, 164, 82, 398, 364, 348, 316, 379, 140, 187, 255, 97, 272, 306, 377, 23, 356, 435, 168, 283, 343, 266, 177, 264, 163, 430, 102, 344, 196, 242, 186, 226, 152, 422, 302, 322, 136, 373, 11, 141, 182, 189, 307, 314, 331, 444, 412, 365, 209, 12, 406, 71, 101, 325, 358, 45, 49, 14, 294, 271, 122, 109, 29, 156, 205, 35, 285, 51, 2, 77, 228, 352, 274, 133, 104, 222, 374, 194, 87, 81, 403, 250, 419, 396, 125, 319, 436, 210, 339, 91, 409, 241, 372, 37, 317, 130, 256, 432, 227, 158, 114, 195, 126, 200, 17, 295, 353, 27, 198, 284, 138, 332, 124, 137, 278, 180, 110, 386, 24, 395, 160, 190, 161, 318, 123, 57, 188, 93, 247, 235, 220, 384, 253, 441, 404, 171, 105, 252, 135, 111, 169, 417, 41, 221, 33, 336, 361, 310, 165, 297, 229, 173, 399, 217, 335, 411, 150, 78, 64, 298, 446, 142, 54, 216, 292, 191, 281, 289, 330, 313, 351, 181, 28, 162, 445, 389, 32, 83, 79, 311, 8, 282, 329, 385, 421, 202, 42, 265, 199, 279, 254, 145, 263, 408, 315, 366, 426, 224, 234, 207, 231, 270, 405, 433, 378, 323, 218, 415, 73, 115, 153, 167, 269, 80, 443, 70, 84, 10, 56, 86, 413, 9, 439, 38, 62, 273, 203, 333, 288, 63, 131, 116, 103, 392, 338, 244, 327, 113, 16, 258, 354, 349, 236, 239, 305, 370, 363, 375, 201, 275, 251, 157, 185, 46, 401, 107, 320, 155, 442, 360, 359, 174, 280, 346, 118, 94, 61, 371, 321, 50, 121, 286, 98, 96, 296, 257, 328, 223, 13, 3, 400, 425, 143, 39, 146, 383, 225, 347, 326, 312, 149, 5, 154, 4]
# shuffled = [385, 197, 317, 353, 78, 88, 329, 310, 222, 435, 149, 252, 331, 235, 289, 412, 122, 44, 208, 13, 350, 183, 400, 102, 192, 162, 6, 15, 131, 253, 100, 283, 109, 48, 217, 406, 318, 89, 367, 84, 287, 39, 193, 94, 173, 293, 325, 391, 351, 41, 152, 83, 332, 229, 196, 224, 298, 297, 160, 259, 348, 286, 251, 79, 278, 370, 85, 311, 199, 127, 357, 8, 423, 384, 249, 42, 76, 416, 26, 341, 11, 118, 218, 444, 51, 146, 260, 177, 115, 103, 372, 167, 352, 189, 270, 315, 410, 389, 303, 116, 347, 381, 35, 307, 438, 312, 242, 60, 7, 212, 171, 25, 275, 38, 126, 395, 2, 40, 239, 276, 14, 426, 164, 337, 398, 9, 299, 157, 65, 24, 96, 57, 37, 36, 236, 280, 261, 316, 319, 104, 214, 138, 119, 112, 225, 255, 424, 156, 63, 443, 359, 223, 292, 245, 380, 268, 399, 120, 360, 304, 81, 66, 244, 264, 70, 166, 320, 369, 258, 207, 301, 300, 180, 382, 296, 436, 213, 408, 415, 413, 75, 111, 396, 421, 147, 113, 21, 159, 231, 194, 393, 313, 176, 128, 322, 91, 140, 257, 371, 145, 151, 188, 68, 34, 209, 124, 411, 232, 158, 53, 12, 219, 178, 3, 295, 133, 33, 439, 1, 64, 110, 238, 430, 49, 428, 226, 31, 19, 56, 390, 54, 417, 345, 150, 333, 431, 132, 240, 73, 383, 211, 59, 77, 407, 170, 440, 125, 246, 247, 80, 191, 288, 342, 216, 23, 277, 210, 335, 141, 282, 30, 90, 97, 368, 248, 234, 105, 106, 58, 114, 47, 237, 358, 206, 144, 432, 338, 343, 274, 20, 377, 16, 46, 418, 155, 271, 427, 43, 404, 142, 302, 179, 98, 99, 324, 29, 153, 402, 433, 82, 204, 354, 339, 375, 362, 139, 344, 294, 18, 121, 184, 4, 241, 175, 101, 291, 200, 87, 148, 134, 215, 376, 387, 205, 61, 284, 92, 403, 71, 309, 290, 181, 401, 334, 394, 168, 379, 269, 154, 185, 262, 273, 203, 397, 86, 198, 72, 420, 17, 355, 281, 130, 45, 321, 267, 50, 445, 93, 135, 143, 330, 67, 305, 174, 5, 272, 27, 254, 220, 328, 364, 346, 69, 392, 95, 165, 366, 374, 28, 230, 356, 195, 243, 117, 108, 266, 425, 187, 201, 422, 256, 172, 137, 161, 442, 55, 326, 361, 107, 123, 405, 265, 285, 233, 414, 446, 221, 441, 136, 429, 419, 227, 10, 279, 327, 340, 308, 52, 129, 323, 250, 306, 437, 32, 62, 386, 163, 373, 182, 74, 169, 314, 228, 378, 22, 434, 336, 190, 365, 409, 263, 363, 186, 388, 202, 349]
# x = 	   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446]
# shuffle(x)

number = input("Enter Number: ")
print(str(number))

# print(x)

# for i in range(20):
# 	random = randrange(len(mamethali))
# 	mamethali3[i] = mamethali[random] 

# print(mamethali3)
# kiswahili = [None] * 492
# english = [None] * 492
# count = 1
# with open('C:\Users\HP\Documents\Code\GitHub\MHENGA\Data\methali2.txt') as f:
#    for line in f:
# 	    print(line)
# 	    if count%2 == 1:
# 			english[count] = line
# 		elif count%2 == 0:
# 			kiswahili[count] = line

# 		count = count + 1
       
# print(english)

# print(kiswahili)