const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(1600, 1600)
const ctx = canvas.getContext('2d')

// Write "Awesome!"
ctx.font = '30px Impact'
ctx.rotate(0.1)
ctx.fillText('Awesome!', 50, 100)
ctx.fillStyle = "blue";
ctx.fillRect(0, 0, canvas.width, canvas.height);

// Draw line under text
var text = ctx.measureText('Awesome!')
ctx.strokeStyle = 'rgba(0,0,0,0.5)'
ctx.beginPath()
ctx.lineTo(50, 102)
ctx.lineTo(50 + text.width, 102)
ctx.stroke()

// Draw cat with lime helmet
loadImage('C:/Users/HP/Documents/Code/GitHub/MHENGA/Images/khanga.jpg').then((image) => {
//   ctx.drawImage(image, 50, 0, 70, 70)

  fs = require('fs');
  // string generated by canvas.toDataURL()
  var img = canvas.toDataURL();
  // strip off the data: url prefix to get just the base64-encoded bytes
  var data = img.replace(/^data:image\/\w+;base64,/, "");
  var buf = new Buffer.from(data, 'base64');
  fs.writeFile('image.png', buf, function(err, result) {
    if(err) console.log('error', err);
  });
})